#pragma once
void practice1_MaxValue();
void practice2_SpecialPrint();
void practice3_Swap2Columns();
void practice4_GreedyRobot();
void practice5_SmallerRow();
void practice6_TriangularMatrix();
void practice7_Transpose();
int main();
